### ISSUE TITLE
BUG - AttributeError: type object 'tqdm' has no attribute 'wrapattr'

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/brainatlas-api#41]
In 
https://github.com/brainglobe/brainatlas-api/blob/73b3e06a597f3843840feb9a9f612c4df9eb5d35/brainatlas_api/utils.py#L42

I get 
```
Traceback (most recent call last):
  File "/Users/federicoclaudi/Documents/Github/BrainRender/workspace.py", line 12, in <module>
    scene = Scene(atlas = 'allen_human_500um_v0.1')  # specify that you want a view from the top
  File "/Users/federicoclaudi/Documents/Github/BrainRender/brainrender/scene.py", line 103, in __init__
    self.atlas = atlasclass(**atlas_kwargs)
  File "/Users/federicoclaudi/miniconda3/envs/brainrender/lib/python3.7/site-packages/brainatlas_api/bg_atlas.py", line 56, in __init__
    self.download_extract_file()
  File "/Users/federicoclaudi/miniconda3/envs/brainrender/lib/python3.7/site-packages/brainatlas_api/bg_atlas.py", line 79, in download_extract_file
    utils.retrieve_over_http(self.remote_url, destination_path)
  File "/Users/federicoclaudi/miniconda3/envs/brainrender/lib/python3.7/site-packages/brainatlas_api/utils.py", line 42, in retrieve_over_http
    with tqdm.wrapattr(
AttributeError: type object 'tqdm' has no attribute 'wrapattr'
```

I propose we move to [rich](https://github.com/willmcgugan/rich) progress bars anyway and ditch tqdm, or at least add a requirement for the `tqdm` version to be >= `tqdm-4.46.1`

**Comment by vigji** [comment]
I am fine with either option! If rich progress bars work fine in both the notebook and the terminal I am happy with using them.

**Comment by FedeClaudi** [comment]
I've replaced this with a rich progess bar. https://github.com/brainglobe/brainatlas-api/pull/49

**Comment by vigji** [comment]
This does not seem to appear in a notebook!

**Comment by FedeClaudi** [comment]
Dammit, I think you're right: https://github.com/willmcgugan/rich/issues/131

Two options:
 - we revert to tqdm 
 - we keep tqdm as a fallback option if the user is using jupyter. What do you and @adamltyson  prefer?

**Comment by vigji** [comment]
Let's also hear @adamltyson but I would find it quite redundant to handle the context ourself on such an "aesthetic" matter given that tqdm can directly do that for us.

**Comment by adamltyson** [comment]
I like rich, but I don’t think it’s worth trying to deal with this ourselves when we can just use tqdm.

**Comment by FedeClaudi** [comment]
sounds good, I reverted back to tqdm

**Comment by willmcgugan** [comment]
Rich progress bars work with Jupyter now :)
